Migrate accessibility rubocop rule `NoRedundantImageAlt` from dotcom to erblint-github
github/rubocop-github pull request #106
Opened 2022-07-28 13:46 UTC by bolonio

## Context

The motivation of [rubocop-github](https://github.com/github/rubocop-github) is to open-source our accessibility rubocop rules so non-GitHub people can benefit from them, have a space to provide comprehensive rule documentation, and also allow rules to be shared between Rails projects.

This PR migrates the accessibility rule `NoRedundantImageAlt` from dotcom to [rubocop-github](https://github.com/github/rubocop-github)

### Related Issue

- https://github.com/github/accessibility/issues/1430

2022-07-28 18:17 UTC, owenniblock approved these changes

2022-07-28 21:01 UTC, khiga8 requested changes
Similar suggestion as https://github.com/github/rubocop-github/pull/105#pullrequestreview-1054745134 🙏

2022-08-01 14:19 UTC, khiga8 approved these changes
Nice job 🎉

2022-08-01 14:19 UTC, khiga8 approved these changes
🚀

2022-08-01 14:21 UTC, merged