Migrate accessibility rubocop rule `NoPositiveTabindex` from dotcom to erblint-github
github/rubocop-github pull request #107
Opened 2022-07-28 14:21 UTC by bolonio

## Context

The motivation of [rubocop-github](https://github.com/github/rubocop-github) is to open-source our accessibility rubocop rules so non-GitHub people can benefit from them, have a space to provide comprehensive rule documentation, and also allow rules to be shared between Rails projects.

This PR migrates the accessibility rule `NoPositiveTabindex` from dotcom to [rubocop-github](https://github.com/github/rubocop-github)

### Related Issue

- https://github.com/github/accessibility/issues/1430

2022-07-28 18:17 UTC, owenniblock approved these changes

2022-07-28 21:02 UTC, khiga8 requested changes
Similar request as https://github.com/github/rubocop-github/pull/106#pullrequestreview-1054745951 🙏

2022-08-01 14:14 UTC, khiga8 commented on test/test_no_positive_tabindex.rb
> +class NoPositiveTabindex < CopTest
Should this be in `test/accessibility/`?

2022-08-01 14:19 UTC, khiga8 approved these changes
🚀

2022-08-01 14:19 UTC, bolonio commented on test/test_no_positive_tabindex.rb
> +
I didn’t put the tests inside a subfolder because `bundle exec rake` doesn’t find them. It only executes the test on the test folder, no subfolders

2022-08-01 14:23 UTC, merged